#!/usr/bin/env bash
# Add a subdomain route for a backend service.
#
# Usage:
#   ./scripts/add-service.sh <name> <upstream-url> [--force]
#
# Examples:
#   ./scripts/add-service.sh gitea http://10.10.10.20:3000
#   ./scripts/add-service.sh jellyfin http://10.10.10.30:8096
#
# Creates config/dynamic/apps/<name>.yml for https://<name>.<DOMAIN>
# Traefik hot-reloads; ACME issues/renews the certificate automatically.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT}/config/base.env"
APPS_DIR="${ROOT}/config/dynamic/apps"
TEMPLATE="${APPS_DIR}/_template.yml"

usage() {
  sed -n '2,12p' "$0" | sed 's/^# \?//'
  exit "${1:-0}"
}

NAME=""
UPSTREAM=""
FORCE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage 0 ;;
    --force) FORCE=1; shift ;;
    -*)
      echo "Unknown option: $1" >&2
      usage 1
      ;;
    *)
      if [[ -z "$NAME" ]]; then
        NAME="$1"
      elif [[ -z "$UPSTREAM" ]]; then
        UPSTREAM="$1"
      else
        echo "Unexpected argument: $1" >&2
        usage 1
      fi
      shift
      ;;
  esac
done

[[ -n "$NAME" && -n "$UPSTREAM" ]] || usage 1

if [[ ! "$NAME" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$ ]]; then
  echo "Service name must be a lowercase DNS label (e.g. gitea, my-app)." >&2
  exit 1
fi

if [[ ! "$UPSTREAM" =~ ^https?:// ]]; then
  echo "Upstream must start with http:// or https://" >&2
  exit 1
fi

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing ${ENV_FILE}." >&2
  echo "Copy config/base.env.example to config/base.env and set DOMAIN." >&2
  exit 1
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

: "${DOMAIN:?DOMAIN must be set in config/base.env}"

OUT="${APPS_DIR}/${NAME}.yml"

if [[ -e "$OUT" && "$FORCE" -ne 1 ]]; then
  echo "Refusing to overwrite ${OUT} (use --force)." >&2
  exit 1
fi

if [[ ! -f "$TEMPLATE" ]]; then
  echo "Missing template: ${TEMPLATE}" >&2
  exit 1
fi

mkdir -p "$APPS_DIR"
HOST="${NAME}.${DOMAIN}"

{
  echo "# Generated by scripts/add-service.sh"
  echo "# https://${HOST}  →  ${UPSTREAM}"
  echo "# Certificate: automatic via Traefik ACME (certResolver: le)"
  echo
  sed \
    -e "s/SERVICE_NAME/${NAME}/g" \
    -e "s/DOMAIN/${DOMAIN}/g" \
    -e "s|UPSTREAM_URL|${UPSTREAM}|g" \
    "$TEMPLATE" | awk 'BEGIN{p=0} /^http:/{p=1} p{print}'
} >"$OUT"

echo "Wrote ${OUT}"
echo "Route:  https://${HOST}"
echo "Next:   ./deploy/sync-config.sh   # if Traefik runs on the LXC"
echo "Cert:   issued/renewed automatically by Traefik (no manual step)"
